name: "Cachix"
on:
  pull_request: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: cachix/install-nix-action@v6
    - uses: cachix/cachix-action@v3
      with:
        name: turbomack
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
